---
- name: Install and configure Nginx on Ubuntu servers
  hosts: web
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Ensure firewall allows HTTP traffic
      ufw:
        rule: allow
        name: "Nginx HTTP"



  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted

      state: started
